/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as RatioCalculatorRouteImport } from './routes/ratio-calculator'
import { Route as RatioRouteImport } from './routes/ratio'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoanCalculatorRouteImport } from './routes/loan-calculator'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as ImplantSupportCalculatorRouteImport } from './routes/implant-support-calculator'
import { Route as HipaaRouteImport } from './routes/hipaa'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DentalImplantRatioCalculatorRouteImport } from './routes/dental-implant-ratio-calculator'
import { Route as DentalImplantPaymentCalculatorRouteImport } from './routes/dental-implant-payment-calculator'
import { Route as DentalImplantLoanCalculatorRouteImport } from './routes/dental-implant-loan-calculator'
import { Route as DentalImplantFinanceCalculatorRouteImport } from './routes/dental-implant-finance-calculator'
import { Route as CostRouteImport } from './routes/cost'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AllOn4CalculatorRouteImport } from './routes/all-on-4-calculator'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const RatioCalculatorRoute = RatioCalculatorRouteImport.update({
  id: '/ratio-calculator',
  path: '/ratio-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const RatioRoute = RatioRouteImport.update({
  id: '/ratio',
  path: '/ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCalculatorRoute = LoanCalculatorRouteImport.update({
  id: '/loan-calculator',
  path: '/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantSupportCalculatorRoute =
  ImplantSupportCalculatorRouteImport.update({
    id: '/implant-support-calculator',
    path: '/implant-support-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const HipaaRoute = HipaaRouteImport.update({
  id: '/hipaa',
  path: '/hipaa',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantRatioCalculatorRoute =
  DentalImplantRatioCalculatorRouteImport.update({
    id: '/dental-implant-ratio-calculator',
    path: '/dental-implant-ratio-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantPaymentCalculatorRoute =
  DentalImplantPaymentCalculatorRouteImport.update({
    id: '/dental-implant-payment-calculator',
    path: '/dental-implant-payment-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantLoanCalculatorRoute =
  DentalImplantLoanCalculatorRouteImport.update({
    id: '/dental-implant-loan-calculator',
    path: '/dental-implant-loan-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalImplantFinanceCalculatorRoute =
  DentalImplantFinanceCalculatorRouteImport.update({
    id: '/dental-implant-finance-calculator',
    path: '/dental-implant-finance-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AllOn4CalculatorRoute = AllOn4CalculatorRouteImport.update({
  id: '/all-on-4-calculator',
  path: '/all-on-4-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/all-on-4-calculator': typeof AllOn4CalculatorRoute
  '/blog': typeof BlogRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cost': typeof CostRoute
  '/dental-implant-finance-calculator': typeof DentalImplantFinanceCalculatorRoute
  '/dental-implant-loan-calculator': typeof DentalImplantLoanCalculatorRoute
  '/dental-implant-payment-calculator': typeof DentalImplantPaymentCalculatorRoute
  '/dental-implant-ratio-calculator': typeof DentalImplantRatioCalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/hipaa': typeof HipaaRoute
  '/implant-support-calculator': typeof ImplantSupportCalculatorRoute
  '/loan': typeof LoanRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/ratio': typeof RatioRoute
  '/ratio-calculator': typeof RatioCalculatorRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/all-on-4-calculator': typeof AllOn4CalculatorRoute
  '/blog': typeof BlogRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cost': typeof CostRoute
  '/dental-implant-finance-calculator': typeof DentalImplantFinanceCalculatorRoute
  '/dental-implant-loan-calculator': typeof DentalImplantLoanCalculatorRoute
  '/dental-implant-payment-calculator': typeof DentalImplantPaymentCalculatorRoute
  '/dental-implant-ratio-calculator': typeof DentalImplantRatioCalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/hipaa': typeof HipaaRoute
  '/implant-support-calculator': typeof ImplantSupportCalculatorRoute
  '/loan': typeof LoanRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/ratio': typeof RatioRoute
  '/ratio-calculator': typeof RatioCalculatorRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/all-on-4-calculator': typeof AllOn4CalculatorRoute
  '/blog': typeof BlogRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cost': typeof CostRoute
  '/dental-implant-finance-calculator': typeof DentalImplantFinanceCalculatorRoute
  '/dental-implant-loan-calculator': typeof DentalImplantLoanCalculatorRoute
  '/dental-implant-payment-calculator': typeof DentalImplantPaymentCalculatorRoute
  '/dental-implant-ratio-calculator': typeof DentalImplantRatioCalculatorRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/hipaa': typeof HipaaRoute
  '/implant-support-calculator': typeof ImplantSupportCalculatorRoute
  '/loan': typeof LoanRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/ratio': typeof RatioRoute
  '/ratio-calculator': typeof RatioCalculatorRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/all-on-4-calculator'
    | '/blog'
    | '/calculator'
    | '/contact'
    | '/cookie-policy'
    | '/cost'
    | '/dental-implant-finance-calculator'
    | '/dental-implant-loan-calculator'
    | '/dental-implant-payment-calculator'
    | '/dental-implant-ratio-calculator'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/hipaa'
    | '/implant-support-calculator'
    | '/loan'
    | '/loan-calculator'
    | '/privacy-policy'
    | '/ratio'
    | '/ratio-calculator'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/all-on-4-calculator'
    | '/blog'
    | '/calculator'
    | '/contact'
    | '/cookie-policy'
    | '/cost'
    | '/dental-implant-finance-calculator'
    | '/dental-implant-loan-calculator'
    | '/dental-implant-payment-calculator'
    | '/dental-implant-ratio-calculator'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/hipaa'
    | '/implant-support-calculator'
    | '/loan'
    | '/loan-calculator'
    | '/privacy-policy'
    | '/ratio'
    | '/ratio-calculator'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/all-on-4-calculator'
    | '/blog'
    | '/calculator'
    | '/contact'
    | '/cookie-policy'
    | '/cost'
    | '/dental-implant-finance-calculator'
    | '/dental-implant-loan-calculator'
    | '/dental-implant-payment-calculator'
    | '/dental-implant-ratio-calculator'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/hipaa'
    | '/implant-support-calculator'
    | '/loan'
    | '/loan-calculator'
    | '/privacy-policy'
    | '/ratio'
    | '/ratio-calculator'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AllOn4CalculatorRoute: typeof AllOn4CalculatorRoute
  BlogRoute: typeof BlogRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CostRoute: typeof CostRoute
  DentalImplantFinanceCalculatorRoute: typeof DentalImplantFinanceCalculatorRoute
  DentalImplantLoanCalculatorRoute: typeof DentalImplantLoanCalculatorRoute
  DentalImplantPaymentCalculatorRoute: typeof DentalImplantPaymentCalculatorRoute
  DentalImplantRatioCalculatorRoute: typeof DentalImplantRatioCalculatorRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FaqRoute: typeof FaqRoute
  HipaaRoute: typeof HipaaRoute
  ImplantSupportCalculatorRoute: typeof ImplantSupportCalculatorRoute
  LoanRoute: typeof LoanRoute
  LoanCalculatorRoute: typeof LoanCalculatorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RatioRoute: typeof RatioRoute
  RatioCalculatorRoute: typeof RatioCalculatorRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratio-calculator': {
      id: '/ratio-calculator'
      path: '/ratio-calculator'
      fullPath: '/ratio-calculator'
      preLoaderRoute: typeof RatioCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratio': {
      id: '/ratio'
      path: '/ratio'
      fullPath: '/ratio'
      preLoaderRoute: typeof RatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-calculator': {
      id: '/loan-calculator'
      path: '/loan-calculator'
      fullPath: '/loan-calculator'
      preLoaderRoute: typeof LoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implant-support-calculator': {
      id: '/implant-support-calculator'
      path: '/implant-support-calculator'
      fullPath: '/implant-support-calculator'
      preLoaderRoute: typeof ImplantSupportCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipaa': {
      id: '/hipaa'
      path: '/hipaa'
      fullPath: '/hipaa'
      preLoaderRoute: typeof HipaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-ratio-calculator': {
      id: '/dental-implant-ratio-calculator'
      path: '/dental-implant-ratio-calculator'
      fullPath: '/dental-implant-ratio-calculator'
      preLoaderRoute: typeof DentalImplantRatioCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-payment-calculator': {
      id: '/dental-implant-payment-calculator'
      path: '/dental-implant-payment-calculator'
      fullPath: '/dental-implant-payment-calculator'
      preLoaderRoute: typeof DentalImplantPaymentCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-loan-calculator': {
      id: '/dental-implant-loan-calculator'
      path: '/dental-implant-loan-calculator'
      fullPath: '/dental-implant-loan-calculator'
      preLoaderRoute: typeof DentalImplantLoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-finance-calculator': {
      id: '/dental-implant-finance-calculator'
      path: '/dental-implant-finance-calculator'
      fullPath: '/dental-implant-finance-calculator'
      preLoaderRoute: typeof DentalImplantFinanceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-on-4-calculator': {
      id: '/all-on-4-calculator'
      path: '/all-on-4-calculator'
      fullPath: '/all-on-4-calculator'
      preLoaderRoute: typeof AllOn4CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AllOn4CalculatorRoute: AllOn4CalculatorRoute,
  BlogRoute: BlogRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CostRoute: CostRoute,
  DentalImplantFinanceCalculatorRoute: DentalImplantFinanceCalculatorRoute,
  DentalImplantLoanCalculatorRoute: DentalImplantLoanCalculatorRoute,
  DentalImplantPaymentCalculatorRoute: DentalImplantPaymentCalculatorRoute,
  DentalImplantRatioCalculatorRoute: DentalImplantRatioCalculatorRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FaqRoute: FaqRoute,
  HipaaRoute: HipaaRoute,
  ImplantSupportCalculatorRoute: ImplantSupportCalculatorRoute,
  LoanRoute: LoanRoute,
  LoanCalculatorRoute: LoanCalculatorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RatioRoute: RatioRoute,
  RatioCalculatorRoute: RatioCalculatorRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
